
sudo: required

dist: trusty

language: c

script:
  - make

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - sudo mv /usr/bin/gcc /usr/bin/gcc.old
        - sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
        - eval "${MATRIX_EVAL}"
    - os: osx
      compiler: clang
